def generate_markdown_docs(repo_url, file_tree, readme, code_structure):
    repo_name = repo_url.split('/')[-1]
    
    doc = f"# Documentation: {repo_name}\n\n"
    doc += f"## Project Overview\n\n"
    doc += f"**Repository:** [{repo_url}]({repo_url})\n\n"
    doc += f"### Summary\n{readme[:300] if readme else 'No README found'}\n\n"
    doc += f"---\n\n"
    doc += f"## Directory Structure\n\n``````\n\n"
    doc += f"---\n\n## Code Structure Analysis\n\n"
    
    doc += f"### Modules\n"
    if code_structure.get("modules"):
        for module in code_structure["modules"][:10]:
            doc += f"- `{module}`\n"
    
    doc += f"\n### Classes\n"
    if code_structure.get("classes"):
        for cls in code_structure["classes"][:15]:
            doc += f"\n#### `{cls['name']}` (from `{cls['module']}`)\n"
            if cls.get("methods"):
                doc += "**Methods:**\n"
                for method in cls["methods"]:
                    doc += f"- `{method}()`\n"
    
    doc += f"\n### Top-Level Functions\n"
    if code_structure.get("functions"):
        for func in code_structure["functions"][:20]:
            args = ", ".join(func.get("args", []))
            doc += f"- `{func['name']}({args})` in `{func['module']}`\n"
    
    doc += f"\n---\n\n*Documentation generated by Codebase Genius*"
    return doc
